export const mockContacts = [
  {
    recordID: '1',
    givenName: 'Ada',
    familyName: 'Lovelace',
    phoneNumbers: [{label: 'mobile', number: '+901111111111'}],
    emailAddresses: [{label: 'work', email: 'ada@lovelace.com'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/women/10.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/women/10.jpg',
  },
  {
    recordID: '2',
    givenName: 'Alan',
    familyName: 'Turing',
    phoneNumbers: [{label: 'mobile', number: '+902222222222'}],
    emailAddresses: [{label: 'home', email: 'alan@turing.org'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/20.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/20.jpg',
  },
  {
    recordID: '3',
    givenName: 'Grace',
    familyName: 'Hopper',
    phoneNumbers: [{label: 'mobile', number: '+903333333333'}],
    emailAddresses: [{label: 'work', email: 'grace@hopper.net'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/women/30.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/women/30.jpg',
  },
  {
    recordID: '4',
    givenName: 'Tim',
    familyName: 'Berners-Lee',
    phoneNumbers: [{label: 'work', number: '+904444444444'}],
    emailAddresses: [{label: 'work', email: 'tim@w3.org'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/40.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/40.jpg',
  },
  {
    recordID: '5',
    givenName: 'Margaret',
    familyName: 'Hamilton',
    phoneNumbers: [{label: 'home', number: '+905555555555'}],
    emailAddresses: [{label: 'home', email: 'margaret@apollo.com'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/women/50.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/women/50.jpg',
  },
  {
    recordID: '6',
    givenName: 'Dennis',
    familyName: 'Ritchie',
    phoneNumbers: [{label: 'mobile', number: '+906666666666'}],
    emailAddresses: [{label: 'work', email: 'dennis@unix.org'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/60.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/60.jpg',
  },
  {
    recordID: '7',
    givenName: 'Linus',
    familyName: 'Torvalds',
    phoneNumbers: [{label: 'mobile', number: '+907777777777'}],
    emailAddresses: [{label: 'work', email: 'linus@linux.org'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/70.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/70.jpg',
  },
  {
    recordID: '8',
    givenName: 'Katherine',
    familyName: 'Johnson',
    phoneNumbers: [{label: 'home', number: '+908888888888'}],
    emailAddresses: [{label: 'home', email: 'katherine@nasa.gov'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/women/80.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/women/80.jpg',
  },
  {
    recordID: '9',
    givenName: 'Steve',
    familyName: 'Jobs',
    phoneNumbers: [{label: 'work', number: '+909999999999'}],
    emailAddresses: [{label: 'work', email: 'steve@apple.com'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/90.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/90.jpg',
  },
  {
    recordID: '10',
    givenName: 'Bill',
    familyName: 'Gates',
    phoneNumbers: [{label: 'mobile', number: '+901010101010'}],
    emailAddresses: [{label: 'work', email: 'bill@microsoft.com'}],
    hasThumbnail: true,
    thumbnailPath: 'https://randomuser.me/api/portraits/med/men/75.jpg',
    avatar: 'https://randomuser.me/api/portraits/med/men/75.jpg',
  },
];
