export const mockContacts = [
  {
    recordID: '1',
    givenName: 'Ada',
    familyName: 'Lovelace',
    phoneNumbers: [{label: 'mobile', number: '(111) 111-1111'}],
    emailAddresses: [{label: 'work', email: 'ada@lovelace.com'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/1',
  },
  {
    recordID: '2',
    givenName: 'Alan',
    familyName: 'Turing',
    phoneNumbers: [{label: 'mobile', number: '(222) 222-2222'}],
    emailAddresses: [{label: 'home', email: 'alan@turing.org'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/2',
  },
  {
    recordID: '3',
    givenName: 'Grace',
    familyName: 'Hopper',
    phoneNumbers: [{label: 'mobile', number: '(333) 333-3333'}],
    emailAddresses: [{label: 'work', email: 'grace@hopper.net'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/3',
  },
  {
    recordID: '4',
    givenName: 'Tim',
    familyName: 'Berners-Lee',
    phoneNumbers: [{label: 'work', number: '(444) 444-4444'}],
    emailAddresses: [{label: 'work', email: 'tim@w3.org'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/4',
  },
  {
    recordID: '5',
    givenName: 'Margaret',
    familyName: 'Hamilton',
    phoneNumbers: [{label: 'home', number: '(555) 555-5555'}],
    emailAddresses: [{label: 'home', email: 'margaret@apollo.com'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/5',
  },
  {
    recordID: '6',
    givenName: 'Dennis',
    familyName: 'Ritchie',
    phoneNumbers: [{label: 'mobile', number: '(666) 666-6666'}],
    emailAddresses: [{label: 'work', email: 'dennis@unix.org'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/6',
  },
  {
    recordID: '7',
    givenName: 'Linus',
    familyName: 'Torvalds',
    phoneNumbers: [{label: 'mobile', number: '(777) 777-7777'}],
    emailAddresses: [{label: 'work', email: 'linus@linux.org'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/7',
  },
  {
    recordID: '8',
    givenName: 'Katherine',
    familyName: 'Johnson',
    phoneNumbers: [{label: 'home', number: '(888) 888-8888'}],
    emailAddresses: [{label: 'home', email: 'katherine@nasa.gov'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/8',
  },
  {
    recordID: '9',
    givenName: 'Steve',
    familyName: 'Jobs',
    phoneNumbers: [{label: 'work', number: '(999) 999-9999'}],
    emailAddresses: [{label: 'work', email: 'steve@apple.com'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/9',
  },
  {
    recordID: '10',
    givenName: 'Bill',
    familyName: 'Gates',
    phoneNumbers: [{label: 'mobile', number: '(000) 000-0000'}],
    emailAddresses: [{label: 'work', email: 'bill@microsoft.com'}],
    hasThumbnail: true,
    thumbnailPath: 'content://com.android.contacts/display_photo/10',
  },
];
