const Routes = {
  TAB: 'TAB',
  STATUS: 'STATUS',
  CALLS: 'CALLS',
  CAMERA: 'CAMERA',
  CHATS: 'CHATS',
  SETTINGS: 'SETTINGS',
  AUTH: 'AUTH',
  CONTACTS: 'CONTACTS',
  PROFILE: 'PROFILE',
  PHONENUMBER: 'Phone Number',
  COUNTRYCODE: 'Select Code',
  USERREGISTIRETIONINFO: 'USER INFO',
};

export default Routes;
